SRC_USERMOD += $(ARDUINO_LIBOPUS_DIR)/src/libogg-1.3.5/src/bitwise.c \
	$(ARDUINO_LIBOPUS_DIR)/src/libogg-1.3.5/src/framing.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/dirac.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/metric_internal.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_auto.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_comments.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_dlist.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_io.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_read.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_seek.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_stream.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_table.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_vector.c \
	$(ARDUINO_LIBOPUS_DIR)/src/liboggz-1.1.1/src/liboggz/oggz_write.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/bands.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/celt.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/celt_decoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/celt_encoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/celt_lpc.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/cwrs.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/entcode.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/entdec.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/entenc.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/kiss_fft.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/laplace.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/mathops.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/mdct.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/modes.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/pitch.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/quant_bands.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/rate.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/celt/vq.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/A2NLSF.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/CNG.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/HP_variable_cutoff.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/LPC_analysis_filter.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/LPC_fit.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/LPC_inv_pred_gain.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/LP_variable_cutoff.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF2A.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_VQ.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_VQ_weights_laroia.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_decode.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_del_dec_quant.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_encode.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_stabilize.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NLSF_unpack.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NSQ.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/NSQ_del_dec.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/PLC.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/VAD.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/VQ_WMat_EC.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/ana_filt_bank_1.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/biquad_alt.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/bwexpander.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/bwexpander_32.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/check_control_input.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/code_signs.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/control_SNR.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/control_audio_bandwidth.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/control_codec.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/debug.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/dec_API.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decode_core.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decode_frame.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decode_indices.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decode_parameters.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decode_pitch.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decode_pulses.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/decoder_set_fs.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/enc_API.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/encode_indices.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/encode_pulses.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/gain_quant.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/init_decoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/init_encoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/inner_prod_aligned.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/interpolate.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/lin2log.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/log2lin.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/pitch_est_tables.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/process_NLSFs.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/quant_LTP_gains.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_down2.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_down2_3.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_private_AR2.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_private_IIR_FIR.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_private_down_FIR.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_private_up2_HQ.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/resampler_rom.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/shell_coder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/sigm_Q15.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/sort.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/stereo_LR_to_MS.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/stereo_MS_to_LR.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/stereo_decode_pred.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/stereo_encode_pred.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/stereo_find_predictor.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/stereo_quant_pred.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/sum_sqr_shift.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/table_LSF_cos.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_LTP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_NLSF_CB_NB_MB.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_NLSF_CB_WB.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_gain.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_other.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_pitch_lag.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/tables_pulses_per_block.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/LTP_analysis_filter_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/LTP_scale_ctrl_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/apply_sine_window_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/autocorr_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/burg_modified_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/corrMatrix_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/encode_frame_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/find_LPC_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/find_LTP_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/find_pitch_lags_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/find_pred_coefs_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/k2a_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/k2a_Q16_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/noise_shape_analysis_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/pitch_analysis_core_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/process_gains_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/regularize_correlations_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/residual_energy16_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/residual_energy_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/schur64_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/schur_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/vector_ops_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/fixed/warped_autocorrelation_FIX.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/LPC_analysis_filter_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/LPC_inv_pred_gain_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/LTP_analysis_filter_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/LTP_scale_ctrl_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/apply_sine_window_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/autocorrelation_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/burg_modified_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/bwexpander_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/corrMatrix_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/encode_frame_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/energy_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/find_LPC_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/find_LTP_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/find_pitch_lags_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/find_pred_coefs_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/inner_product_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/k2a_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/noise_shape_analysis_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/pitch_analysis_core_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/process_gains_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/regularize_correlations_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/residual_energy_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/scale_copy_vector_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/scale_vector_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/schur_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/sort_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/warped_autocorrelation_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/silk/float/wrappers_FLP.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/analysis.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/mapping_matrix.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/mlp.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/mlp_data.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_decoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_encoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_multistream.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_multistream_decoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_multistream_encoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_projection_decoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/opus_projection_encoder.c \
	$(ARDUINO_LIBOPUS_DIR)/src/opus-1.3.1/src/repacketizer.c